### ISSUE TITLE
Script feature to add game information to ES's gamelist.xml

### ISSUE THREAD

**Issue by UDb23** [UDb23/rpie-ovl#21]
Info.txt may include specific line to add corresponding game data to `gamelist.xml`.
`addgamedata = yes`
If this line is found in info.txt, script should check if in same folder a `gamedata.txt` exists.
If `gamedata.txt`exists, extract data and write into `gamelist.xml`
If `gamedata.txt`does NOT exist, pull data from global game data file (includes all .78 roms; I can provide this file in the Repo in whatever structure/format needed; current file available [here](https://retropie.org.uk/forum/topic/6056/manually-generate-mame2003-gamelist/49)) and write into `gamelist.xml`

gamedata.txt would allow people to create their own game data (or translated version for local language).

Game data basically means game name and description (`<desc>` in gamelist.xml)

**Comment by meleu** [comment]
I've put this feature request in the new script repo: https://github.com/meleu/rpie-art/issues/2
You can close this issue here. ;-)

**Comment by UDb23** [comment]
great, thanks !
