### ISSUE TITLE
cleaner repo

### ISSUE THREAD

**Issue by meleu** [UDb23/rpie-ovl#44]
hey mate, I would like to suggest you to create another repo for temporary or non-overlay related files. 

I'm saying that because your repo (rpie-ovl) is downloaded/cloned by `rpie-art` users and there are some files here unrelated with our original intention, don't you agree?

Please, don't take it like I'm wanting to say what you should do on your own repo, it's just a suggestion! :sweat_smile: 

I did a similar thing for my sporadic scripts, codes, configs, whatever: https://github.com/meleu/share

Cheers!

**Comment by UDb23** [comment]
As usual it's a good suggestion. Will do cleanup asap.
