### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by WXDFever** [UDb23/rpie-ovl#46]
Hey, buddy. I've been searching for some overlays and found you did quite a good job. Love your overlays. So my question is, is there any way (a script perhaps) to set different overlay for each different game when I am launching the game? For now, I just lauch the game then select the overlay I want. 

P.S. I am a newbie, not sure if it's a stupid question. 
Thanks for your support on overlays!

**Comment by UDb23** [comment]
What emulator and operating system are you using ?
For Retropie you can set different overlays for each game with @meleu 's [script](https://github.com/meleu/rpie-art)

**Comment by WXDFever** [comment]
@UDb23 Thanks for your reply. Yes, I am using retropie
