### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by WXDFever** [UDb23/rpie-ovl#48]
Hello, Buddy.

Not sure if it's ok to request some overlays, but would you please make some overlays for arcade games, especially for CPS1 and CPS2 games?

Thanks

**Comment by UDb23** [comment]
Requests are welcome. Any specific CPS1/CPS2 game you'd like ?

**Comment by WXDFever** [comment]
Thanks for your attention. Here are the overlays for arcade games I like (based on rom names):

CPS1：
wof
kod
knights
captcomm
ffight
msword
punisher

CPS2:
ddsomu
ddtodu

Neo-Geo
strhoop

PGM:
kov

Hope it will not be a trouble for you

**Comment by meleu** [comment]
off topic but not that much:

> msword
> punisher

I made a set of achievements for Magic Sword (SNES port) and The Punisher (MegaDrive port).
You can check them out here:
http://retroachievements.org/game/1012
http://retroachievements.org/game/574

Sorry for the off-topic 😅 

Cheers!

**Comment by WXDFever** [comment]
@meleu Great achievements. Hmm, but I am a noob, not sure how does this work?

**Comment by meleu** [comment]
If you're using RetroPie, just create an account on retroachievements.org and then follow the instructions here:
https://github.com/retropie/retropie-setup/wiki/RetroAchievements

**Comment by WXDFever** [comment]
@meleu Thanks for your info, it looks great, I will get it a try later :+1:

**Comment by UDb23** [comment]
msword: so you're not requesting an overlay for Microsoft word, lol !
Jokes aside will have a look at those games and see if I can make some overlays.

**Comment by WXDFever** [comment]
@UDb23 lol, msword, I didn't noticed that

**Comment by WXDFever** [comment]
@UDb23 @meleu one more thing, do you guys know where I can download these
![123](https://user-images.githubusercontent.com/29010142/35139975-58e0822a-fced-11e7-8280-b4e65c6448a4.jpg)

**Comment by UDb23** [comment]
[here](http://www.neogeosoft.com/?section=view&game=garou)
High res moves strip. ;-)

**Comment by WXDFever** [comment]
@UDb23 great, thanks for your reply.  Hmm, the website is just for neo-geo games moves strip, is there any other website for cps and other games?（instruction strip will also be good）

Btw, I bought s1945 and gunbird on my NS, when I was playing the game, I found it supports something like overlay(not sure if it's called that), I will try to make screenshots and send them to you, you may take a look to see if it helps to make overlay,lol

**Comment by WXDFever** [comment]
[1.23.zip](https://github.com/UDb23/rpie-ovl/files/1658165/1.23.zip)
Well, I connected my ns with my tv and took some screenshots, I am not good at using photoshop, so here are the original screenshots. So in the middle of the picture is the gameplay screen, left and right are information about bombs and other stuff. Not sure if these screenshots can help you to make overlays, I just uploaded here,lol.

updated with png format(without game screen)
[1.24.zip](https://github.com/UDb23/rpie-ovl/files/1658299/1.24.zip)

**Comment by UDb23** [comment]
Thanks for the screenshots. Generally good quality (high res) scans are needed to make the overlays. Other sources can help for missing parts but completely redrawing graphics is a no go.

Started working on Magic Sword's overlay.

**Comment by WXDFever** [comment]
great, so msword is on the way, lol

**Comment by UDb23** [comment]
Magic Sword created and available in the Repo (arcade)

**Comment by WXDFever** [comment]
great, thanks for your hard work, lol
