### ISSUE TITLE
SNES overlays won't install with script

### ISSUE THREAD

**Issue by daftinquisitor** [UDb23/rpie-ovl#50]
I have both Illusion of Gaia and Super Mario RPG on my retropie. When I try to use the script to install the custom overlays for each, it returns an error saying it can't find the games. The one for Galaga in Arcade worked fine, but not the SNES ones. I checked to make sure the naming scheme is the same, unless it's expecting zipped files instead of .sfc files.

**Comment by UDb23** [comment]
I guess you already checked your rom names are exactly the same as the cfgs (case sensitive) ?
These specific overlays were made by @lilbud : best way is to ask him (on github or Retropie forum).

**Comment by lilbud** [comment]
Or just ask me here :)

I think it will only work with zip files. Not quite sure how the overlay config works exactly. Either try zipping your roms or changing the name to .sfc.cfg.
